spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    data: classpath:db/data-h2.sql
    url: jdbc:mysql://localhost/workflow?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  boot:
    admin:
      context-path: /admin

  jackson:
    date-format:  'yyyy-MM-dd HH:mm:ss'
    time-zone:  GMT+8

  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: scheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc


mybatis-plus:
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.ladtor: debug